# ===========================
# Material Theme — Kitty Terminal
# ProjectKittyThemes
# ===========================

# Colors
background            #263238
foreground            #eceff1
cursor                #eceff1
selection_background  #eceff138
selection_foreground  #eceff1

# Black
color0   #263238
color8   #546e7a

# Red
color1   #ef5350
color9   #ef9a9a

# Green
color2   #81c784
color10  #a5d6a7

# Yellow
color3   #ffca28
color11  #ffe082

# Blue
color4   #42a5f5
color12  #90caf9

# Magenta
color5   #ab47bc
color13  #ce93d8

# Cyan
color6   #26c6da
color14  #80deea

# White
color7   #eceff1
color15  #ffffff
