# ===========================
# Catppuccin Latte — Kitty Terminal
# ProjectKittyThemes
# ===========================

# Colors
background            #eff1f5
foreground            #4c4f69
cursor                #d20f39
selection_background  #d20f3940
selection_foreground  #4c4f69

# Black
color0   #6c6f85
color8   #9ca0b0

# Red
color1   #d20f39
color9   #d20f39

# Green
color2   #40a02b
color10  #40a02b

# Yellow
color3   #df8e1d
color11  #df8e1d

# Blue
color4   #7287fd
color12  #7287fd

# Magenta
color5   #8839ef
color13  #8839ef

# Cyan
color6   #179299
color14  #179299

# White
color7   #bcc0cc
color15  #ccd0da
