# ===========================
# Rosé Pine — Alacritty
# ProjectKittyThemes
# ===========================

[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.cursor]
cursor = "#e0def4"
text   = "#191724"

[colors.selection]
background = "#26233a"
text       = "#e0def4"

[colors.normal]
black   = "#26233a"
red     = "#eb6f92"
green   = "#9ccfd8"
yellow  = "#f6c177"
blue    = "#31748f"
magenta = "#c4a7e7"
cyan    = "#9ccfd8"
white   = "#e0def4"

[colors.bright]
black   = "#524f67"
red     = "#eb6f92"
green   = "#9ccfd8"
yellow  = "#f6c177"
blue    = "#31748f"
magenta = "#c4a7e7"
cyan    = "#9ccfd8"
white   = "#f2f0eb"
