# ===========================
# Iceberg — Kitty Terminal
# ProjectKittyThemes
# ===========================

# Colors
background            #161821
foreground            #c8c8c8
cursor                #c8c8c8
selection_background  #c8c8c838
selection_foreground  #c8c8c8

# Black
color0   #161821
color8   #6e7080

# Red
color1   #e27878
color9   #e49191

# Green
color2   #9ece9a
color10  #b0d09e

# Yellow
color3   #e4c46a
color11  #ebd386

# Blue
color4   #7ca5e3
color12  #94b7e5

# Magenta
color5   #b87fc4
color13  #c99ed3

# Cyan
color6   #74b0c0
color14  #8fc9cf

# White
color7   #c8c8c8
color15  #d8d8d8
