# ===========================
# One Dark Pro — Alacritty
# ProjectKittyThemes
# ===========================

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.cursor]
cursor = "#528bff"
text   = "#282c34"

[colors.selection]
background = "#3e4451"
text       = "#abb2bf"

[colors.normal]
black   = "#282c34"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ffffff"
