# ===========================
# Ayu Light — Kitty Terminal
# ProjectKittyThemes
# ===========================

# Colors
background            #fafafa
foreground            #5c5c5c
cursor                #5c5c5c
selection_background  #5c5c5c38
selection_foreground  #5c5c5c

# Black
color0   #fafafa
color8   #8a8a8a

# Red
color1   #ff3333
color9   #ff5555

# Green
color2   #86b300
color10  #86b300

# Yellow
color3   #c29702
color11  #c29702

# Blue
color4   #0071d1
color12  #0071d1

# Magenta
color5   #7a51d8
color13  #7a51d8

# Cyan
color6   #2b7ea3
color14  #2b8282

# White
color7   #5c5c5c
color15  #3d3d3d
