# ===========================
# Ayu Dark — Kitty Terminal
# ProjectKittyThemes
# ===========================

# Colors
background            #0a0e14
foreground            #b3b1ad
cursor                #b3b1ad
selection_background  #b3b1ad38
selection_foreground  #b3b1ad

# Black
color0   #0a0e14
color8   #626a70

# Red
color1   #ff3333
color9   #ff5555

# Green
color2   #87d96c
color10  #85d96c

# Yellow
color3   #ffb454
color11  #ffb86c

# Blue
color4   #59c2ff
color12  #59c2ff

# Magenta
color5   #c2a3ff
color13  #c2a3ff

# Cyan
color6   #6ec2fa
color14  #7fd962

# White
color7   #b3b1ad
color15  #ffffff
